name: Notify new release
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: notify-new-release
      with:
        result-encoding: string
        retries: 3
        retry-exempt-status-codes: 400,401
        github-token: ${{ secrets.TURBOPACK_TEST_TOKEN }}
        script: |
          github.request('POST /repos/{owner}/{repo}/dispatches', {
            owner: 'vercel',
            repo: 'turbo',
            event_type: 'nextjs-release',
            client_payload: {
              version: context.ref
            }
          })
